name: Test Trigger Script

on:
    repository_dispatch:
        types: [trigger-tests]


jobs:
    report-creation:
        runs-on: ubuntu-latest

        steps:
        - name: Intialize NPM
          uses: actions/checkout@v4
        
        - name: Install Dependencies
          run: npm install

        - name: Run Cypress
          uses: cypress-io/github-action@v6  